### ISSUE TITLE
caddy runs as root

### ISSUE THREAD

**Issue by joshix** [joshix/caddybox#18]
As of #16, caddy runs as `UID 0` (root) in the container

Caddy must bind privileged ports to do TLS most simply. This requires either user privileges, like running as `root`, or using the linux _capabilities_ facility to grant certain powers to the executable binary itself, e.g.,

``` sh
  $ setcap cap_net_bind_service=+ep /bin/caddy
```

An external `setcap` on `rootfs/bin/caddy` is not reflected into the container. Running `setcap` inside the container at `docker build` time requires a distro base image, like Alpine. See the [`setcap` branch](https://github.com/joshix/caddybox/tree/setcap) for an exploration of this approach.

Other potential solutions:
- Caddybox could run `/bin/caddy` as non-root and only bind unprivileged ports inside the container. Then docker proxy listens on the standard ports and redirects (as in the non-LE examples in the [README](https://github.com/joshix/caddybox/blob/master/README.md)).
- (Upstream) Caddy could drop privileges after binding ports: Blocked on a [golang issue with dropping privileges among goroutines](https://github.com/golang/go/issues/1435)
- (Upstream) Docker and linux could completely implement UID namespaces

**Comment by joshix** [comment]
Related #3 : There has been some indecision about this. :)

**Comment by joshix** [comment]
Related https://github.com/mholt/caddy/issues/528

**Comment by joshix** [comment]
See _DNS Challenge_ in [Caddy 0.9 beta notes](https://forum.caddyserver.com/t/caddy-0-9-beta-version-available/146?u=matt) for a potential resolution.

**Comment by joshix** [comment]
On the rkt/ACI branch, ref https://github.com/coreos/rkt/blob/master/Documentation/capabilities-guide.md

**Comment by ryanj** [comment]
I'm hitting this issue as well. :(

I'm in favor of the first potential solution, outlined above: 
> Caddybox could run /bin/caddy as non-root and only bind unprivileged ports inside the container

I don't think anyone needs to use privileged ports (given that docker allows mapping to a different port externally)

**Comment by joshix** [comment]
@ryanj I was too, if you follow the litany of indecision back through issues and PRs. ;)

The problem is that [caddy's automatic HTTPS expects to bind 80 and 443](https://caddyserver.com/docs/automatic-https). I want to support it in the simple single-docker-host case.

**Comment by joshix** [comment]
https://github.com/caddyserver/dnsproviders

**Comment by hartwork** [comment]
If anyone's interested, here's my take at turning a Caddy Docker image ([`abiosoft/caddy`](https://github.com/abiosoft/caddy-docker) in this case) to non-root while keeping binding to port 80/443 and hence automatic SSL alive, using `setcap`: https://github.com/hartwork/docker-ssl-reverse-proxy/commit/75b07a158d3da45d2eb6d1dc141bc11ac46e8c3d

**Comment by joshix** [comment]
This way works, if your container builds `FROM alpine` or some other distro base image. I [experimented with it in the setcap branch](https://github.com/joshix/caddybox/blob/0889f627426f2f77642b53360a6bbb5e2820966d/Dockerfile#L5-L7). But since Caddybox intends to illustrate a minimal, distro-less container, I decided not to adopt a distribution, even one as small as Alpine, and to [keep `FROM scratch`. So there's no `setcap` here and no shell to run `setcap` in.](https://github.com/joshix/caddybox/issues/18#issue-123195062)

**Comment by hartwork** [comment]
What about basing on alpine and using `rm` to delete everything but Caddy including the `rm` binary as the last `RUN` in `Dockerfile`? I believe that could work to have both an image with just caddy without a distro around _and_ still be able to run `setcap` on the eventual Caddy binary. What do you think?

**Comment by joshix** [comment]
As of #46 caddy runs under UID:GID numbers that conventionally mean `nobody`.
