### ISSUE TITLE
running caddy with auto https

### ISSUE THREAD

**Issue by badoet** [joshix/caddybox#20]
tried to run 

```
$ ls /home/j/site
Caddyfile
index.html
$ cat /home/j/site/Caddyfile
lecaddybox.wood-racing.com
  tls j@joshix.com
$ docker run --name com.wood-racing.lecaddybox -d \
-p 80:80 -p 443:443 \
-v /home/j/site:/var/www/html:ro \
-v /home/j/dotcaddy:/.caddy:rw \
joshix/caddy
```

i get this error message:

```
2015/12/21 03:24:16 [blog.badoet.com] failed to get certificate: The server could not validate our request.
Activating privacy features...
```

Did i miss a step?

**Comment by joshix** [comment]
I notice that `blog.badoet.com` has two A records (aka round robin dns). The ACME spec says [a certificate server using _simple http_ validation can dial back any of a domain name's A or AAAA records](https://github.com/letsencrypt/acme-spec/blob/master/draft-barnes-acme.md#simple-http) it finds for the domain being validated.

**Comment by joshix** [comment]
Provisionally closing as related to the rr dns.
