### ISSUE TITLE
USER instruction for building secure Docker images

### ISSUE THREAD

**Issue by joelchen** [joshix/caddybox#26]
Should there be a USER instruction included in the Dockerfile for added security as described in https://www.youtube.com/watch?v=LmUw2H6JgJo?

**Comment by joshix** [comment]
Short answer: Yes, but...
Longer answer: See (and this issue is duplicate of) #18 and #3. Historically we ran as a contrived UID 22015.

**Comment by joshix** [comment]
Closed duplicate. Advice/PRs against #18 welcome. :-)

**Comment by joshix** [comment]
Closed duplicate. Advice/PRs against #18 welcome. :-)
