### ISSUE TITLE
PreferServerCipherSuites

### ISSUE THREAD

**Issue by irony** [joshix/caddybox#30]
I constantly get this error when trying to redeploy my services:
"cannot both use PreferServerCipherSuites and not use it"

Does anyone else experience similar problems?

**Comment by metalmatze** [comment]
I do right now. Trying to figure this out.

**Comment by joshix** [comment]
Sorry for the long delay in response.

This error message lives at https://github.com/mholt/caddy/blob/master/caddytls/config.go#L261, fwiw.

Are either of you [specifying `ciphers` in your Caddyfile](https://caddyserver.com/docs/tls)?

Are you using certificates from the LE support, or specifying your own certs?

Edited to add:
I finally got an update out today with the latest Caddy binary, v0.9.1, so please grab that image from Docker hub or quay.io/josh_wood/caddy:v0.9.1 and we'll go from there.

**Comment by joshix** [comment]
closing - inactive across two version updates
