### ISSUE TITLE
Add compilation from source to repo

### ISSUE THREAD

**Issue by steelbrain** [joshix/caddybox#38]
It's a huge leap of faith to use prebuilt binaries from an untrusted source in production.

Is it possible to have the scripts in this repo that you use to generate the binary?

**Comment by joshix** [comment]
@steelbrain The binary at `rootfs/bin/caddy` (`/bin/caddy` within the resulting container image), is that from the [Caddy project's Linux amd64 build](https://github.com/mholt/caddy/releases), with the specific tarball [named in each Caddybox release](https://github.com/joshix/caddybox/releases). It isn't re-built from source.

**Comment by steelbrain** [comment]
Aha, thanks for the explanation!

**Comment by joshix** [comment]
v0.10.10 returned to building caddy from source, reopening this issue.

**Comment by joshix** [comment]
v.0.10.11 adds a simple [build script][bs] for building `rootfs/bin/caddy` from the upstream source.

[bs]: https://github.com/joshix/caddybox/blob/master/buildcaddy.bash

**Comment by joshix** [comment]
v0.10.11 adds a simple [build script][bs] for building `rootfs/bin/caddy` from the upstream source.

[bs]: https://github.com/joshix/caddybox/blob/master/buildcaddy.bash
