### ISSUE TITLE
Update to Caddy 0.10

### ISSUE THREAD

**Issue by whs** [joshix/caddybox#39]
Caddy 0.10 was released on [21 April 2017](https://github.com/mholt/caddy/releases/tag/v0.10.0). Please update the container.

Thanks!

**Comment by joshix** [comment]
Thanks for your patience, @whs. A [new Caddybox based on Caddy v0.10.3 has been released](https://github.com/joshix/caddybox/releases/tag/v0.10.3).

**Comment by whs** [comment]
Thanks!
