### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by YouveGotMeowxy** [joshix/caddybox#47]
I have 2 quick questions before I try this container that I'm hoping you can answer.

1. Can I still add plugins that I use to it? If so, how?
2. I noticed that the Caddyfile is in the root web folder, I make frequent changes to mine, is there still a way to bind it to the local host so I can do quick edits to it w/out having to copy it (via the cp command) to the container after each little change?

Thanks!

**Comment by YouveGotMeowxy** [comment]
Helllooooooooooo

Is there anybody out there .....

**Comment by joshix** [comment]
I'll save you my plea of "Kubecon is crazy" and instead just thank you for your patience while I took two weeks to see your questions.
1. You'd need to rebuild the caddy binary to add plugins, and if you're using plugins, this might not be the right container image for you. I'd point you toward https://github.com/abiosoft/caddy-docker, which has a build step that you can adjust to amend the list of plugins.
2. Yes, you can bind some local file over the included Caddyfile (and I need to update the README to indicate this. The inclusion of a default Caddyfile in the image is a fairly recent change.)

**Comment by joshix** [comment]
Closed answered, inactive.
